// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlvlhKHyyjfxAVgTSxuBSGdDB5qquVk6c',
    appId: '1:1077201570871:web:7d43569d16344c94bb03b2',
    messagingSenderId: '1077201570871',
    projectId: 'xacai-delivery-prod',
    authDomain: 'xacai-delivery-prod.firebaseapp.com',
    storageBucket: 'xacai-delivery-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxEh0DnGyOCvf4Hs708D4HDw3EYof23Cs',
    appId: '1:1077201570871:android:7b062e2601252ca3bb03b2',
    messagingSenderId: '1077201570871',
    projectId: 'xacai-delivery-prod',
    storageBucket: 'xacai-delivery-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwWRiX4H8OFzQsTCC7UezTRBQ0p3nMeyw',
    appId: '1:1077201570871:ios:d011e9c6c2c79d0fbb03b2',
    messagingSenderId: '1077201570871',
    projectId: 'xacai-delivery-prod',
    storageBucket: 'xacai-delivery-prod.firebasestorage.app',
    iosBundleId: 'com.example.clientApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwWRiX4H8OFzQsTCC7UezTRBQ0p3nMeyw',
    appId: '1:1077201570871:ios:d011e9c6c2c79d0fbb03b2',
    messagingSenderId: '1077201570871',
    projectId: 'xacai-delivery-prod',
    storageBucket: 'xacai-delivery-prod.firebasestorage.app',
    iosBundleId: 'com.example.clientApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlvlhKHyyjfxAVgTSxuBSGdDB5qquVk6c',
    appId: '1:1077201570871:web:1bf839ce09c9107dbb03b2',
    messagingSenderId: '1077201570871',
    projectId: 'xacai-delivery-prod',
    authDomain: 'xacai-delivery-prod.firebaseapp.com',
    storageBucket: 'xacai-delivery-prod.firebasestorage.app',
  );
}
