export const schemaStatements: string[] = [
    `CREATE TABLE IF NOT EXISTS restaurants (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        slug TEXT UNIQUE NOT NULL,
        phone TEXT,
        email TEXT,
        status TEXT DEFAULT 'active',
        plan TEXT DEFAULT 'trial',
        mode TEXT DEFAULT 'saas',
        subscription_plan TEXT DEFAULT 'starter',
        subscription_status TEXT DEFAULT 'active',
        onboarding_step INTEGER DEFAULT 0,
        owner_id TEXT,
        city TEXT,
        address TEXT,
        logo_url TEXT,
        banner_url TEXT,
        active INTEGER DEFAULT 1,
        description TEXT,
        whatsapp TEXT,
        primary_color TEXT DEFAULT '#9333ea',
        secondary_color TEXT DEFAULT '#ffffff',
        pricing_rules TEXT,
        yield_balance_cents INTEGER DEFAULT 0,
        cnpj TEXT,
        store_status TEXT DEFAULT 'open',
        prep_time_minutes INTEGER DEFAULT 30,
        delivery_fee_cents INTEGER DEFAULT 500,
        min_order_cents INTEGER DEFAULT 0,
        slogan TEXT,
        theme TEXT DEFAULT 'light',
        theme_id TEXT,
        font_family TEXT,
        temp_close_reason TEXT,
        can_accept_orders INTEGER DEFAULT 1,
        facebook_pixel_id TEXT,
        google_analytics_id TEXT,
        tiktok_pixel_id TEXT,
        custom_domain TEXT,
        timezone TEXT,
        opening_hours TEXT,
        max_orders_simultaneous INTEGER,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS menu_items (
        id TEXT PRIMARY KEY,
        restaurant_id TEXT NOT NULL,
        name TEXT NOT NULL,
        description TEXT,
        price_cents INTEGER NOT NULL,
        category TEXT,
        tags TEXT,
        available INTEGER DEFAULT 1,
        image_url TEXT,
        out_of_stock INTEGER DEFAULT 0,
        hidden INTEGER DEFAULT 0,
        sort_order INTEGER DEFAULT 0,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS customers (
        id TEXT PRIMARY KEY,
        restaurant_id TEXT NOT NULL,
        name TEXT NOT NULL,
        phone TEXT NOT NULL,
        email TEXT,
        otp_code TEXT,
        otp_expires_at DATETIME,
        last_order_at DATETIME,
        total_orders INTEGER DEFAULT 0,
        total_spent_cents INTEGER DEFAULT 0,
        tags TEXT,
        notes TEXT,
        referral_code TEXT,
        birthday TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(restaurant_id, phone)
    )`,
    `CREATE TABLE IF NOT EXISTS orders (
        id TEXT PRIMARY KEY,
        restaurant_id TEXT NOT NULL,
        customer_id TEXT NOT NULL,
        status TEXT NOT NULL,
        items TEXT NOT NULL,
        subtotal_cents INTEGER NOT NULL,
        delivery_fee_cents INTEGER NOT NULL,
        total_cents INTEGER NOT NULL,
        discount_cents INTEGER DEFAULT 0,
        coupon_code TEXT,
        address_text TEXT NOT NULL,
        payment_status TEXT DEFAULT 'pending_payment',
        payment_method TEXT DEFAULT 'pix',
        payment_provider TEXT,
        payment_qr_code TEXT,
        payment_qr_base64 TEXT,
        payment_reference TEXT,
        transaction_id TEXT,
        customer_name TEXT,
        customer_phone TEXT,
        source TEXT DEFAULT 'online',
        notes TEXT,
        external_id TEXT,
        tax_id TEXT,
        is_surge INTEGER DEFAULT 0,
        is_happy_hour INTEGER DEFAULT 0,
        rating INTEGER,
        feedback TEXT,
        paid_at DATETIME,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS coupons (
        id TEXT PRIMARY KEY,
        restaurant_id TEXT NOT NULL,
        code TEXT NOT NULL,
        description TEXT,
        type TEXT NOT NULL DEFAULT 'flat',
        discount_value INTEGER NOT NULL,
        min_order_cents INTEGER DEFAULT 0,
        max_uses INTEGER DEFAULT 0,
        used_count INTEGER DEFAULT 0,
        active INTEGER DEFAULT 1,
        expires_at DATETIME,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(restaurant_id, code)
    )`,
    `CREATE TABLE IF NOT EXISTS drivers (
        id TEXT PRIMARY KEY,
        restaurant_id TEXT NOT NULL,
        name TEXT NOT NULL,
        phone TEXT NOT NULL,
        vehicle TEXT,
        status TEXT DEFAULT 'active',
        access_code TEXT,
        is_online INTEGER DEFAULT 0,
        rating REAL DEFAULT 5,
        last_dispatch_at DATETIME,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS option_groups (
        id TEXT PRIMARY KEY,
        restaurant_id TEXT NOT NULL,
        menu_item_id TEXT NOT NULL,
        name TEXT NOT NULL,
        required INTEGER DEFAULT 0,
        min_select INTEGER DEFAULT 0,
        max_select INTEGER DEFAULT 1,
        sort_order INTEGER DEFAULT 0,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS option_items (
        id TEXT PRIMARY KEY,
        restaurant_id TEXT NOT NULL,
        option_group_id TEXT NOT NULL,
        name TEXT NOT NULL,
        price_cents INTEGER NOT NULL,
        available INTEGER DEFAULT 1,
        sort_order INTEGER DEFAULT 0,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS restaurant_settings (
        id TEXT PRIMARY KEY,
        restaurant_id TEXT NOT NULL,
        key TEXT NOT NULL,
        value TEXT,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(restaurant_id, key)
    )`,
    `CREATE TABLE IF NOT EXISTS cash_sessions (
        id TEXT PRIMARY KEY,
        restaurant_id TEXT NOT NULL,
        user_id TEXT,
        initial_value_cents INTEGER DEFAULT 0,
        final_value_cents INTEGER,
        expected_value_cents INTEGER,
        opened_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        closed_at DATETIME,
        opening_amount INTEGER DEFAULT 0,
        closing_amount INTEGER,
        status TEXT DEFAULT 'open'
    )`,
    `CREATE TABLE IF NOT EXISTS system_logs (
        id TEXT PRIMARY KEY,
        level TEXT NOT NULL,
        message TEXT NOT NULL,
        context TEXT,
        timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS payment_logs (
        id TEXT PRIMARY KEY,
        order_id TEXT NOT NULL,
        provider TEXT NOT NULL,
        payment_reference TEXT,
        status TEXT NOT NULL,
        payload TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS qr_campaigns (
        id TEXT PRIMARY KEY,
        restaurant_id TEXT NOT NULL,
        name TEXT NOT NULL,
        discount_value REAL,
        discount_type TEXT,
        landing_slug TEXT UNIQUE,
        scan_count INTEGER DEFAULT 0,
        conversions INTEGER DEFAULT 0,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS loyalty_points (
        id TEXT PRIMARY KEY,
        restaurant_id TEXT NOT NULL,
        customer_id TEXT NOT NULL,
        points INTEGER NOT NULL,
        type TEXT NOT NULL,
        description TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS customer_segments (
        id TEXT PRIMARY KEY,
        restaurant_id TEXT NOT NULL,
        name TEXT NOT NULL,
        description TEXT,
        query_json TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS campaigns (
        id TEXT PRIMARY KEY,
        restaurant_id TEXT NOT NULL,
        name TEXT NOT NULL,
        segment_id TEXT,
        type TEXT,
        status TEXT DEFAULT 'draft',
        message_template TEXT,
        scheduled_at DATETIME,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS marketing_triggers (
        id TEXT PRIMARY KEY,
        restaurant_id TEXT NOT NULL,
        type TEXT NOT NULL,
        active INTEGER DEFAULT 1,
        days_inactive INTEGER,
        order_count INTEGER,
        discount_type TEXT,
        discount_value INTEGER,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS customer_campaigns (
        id TEXT PRIMARY KEY,
        restaurant_id TEXT NOT NULL,
        customer_id TEXT NOT NULL,
        type TEXT NOT NULL,
        coupon_id TEXT,
        status TEXT DEFAULT 'sent',
        scheduled_for DATETIME,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS campaign_logs (
        id TEXT PRIMARY KEY,
        campaign_id TEXT,
        customer_id TEXT NOT NULL,
        status TEXT NOT NULL,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS inventory_items (
        id TEXT PRIMARY KEY,
        restaurant_id TEXT NOT NULL,
        name TEXT NOT NULL,
        sku TEXT,
        current_qty INTEGER DEFAULT 0,
        min_qty INTEGER DEFAULT 0,
        min_stock INTEGER DEFAULT 0,
        unit TEXT,
        cost_cents INTEGER DEFAULT 0,
        supplier TEXT,
        category TEXT,
        active INTEGER DEFAULT 1,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS inventory_movements (
        id TEXT PRIMARY KEY,
        restaurant_id TEXT NOT NULL,
        inventory_item_id TEXT NOT NULL,
        type TEXT NOT NULL,
        qty REAL NOT NULL,
        reason TEXT,
        ref_order_id TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS suppliers (
        id TEXT PRIMARY KEY,
        restaurant_id TEXT NOT NULL,
        name TEXT NOT NULL,
        contact_name TEXT,
        phone TEXT,
        email TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS recipes (
        id TEXT PRIMARY KEY,
        restaurant_id TEXT NOT NULL,
        menu_item_id TEXT NOT NULL,
        name TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS recipe_items (
        id TEXT PRIMARY KEY,
        restaurant_id TEXT NOT NULL,
        recipe_id TEXT NOT NULL,
        inventory_item_id TEXT NOT NULL,
        qty REAL NOT NULL,
        unit TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS financial_entries (
        id TEXT PRIMARY KEY,
        restaurant_id TEXT NOT NULL,
        cash_session_id TEXT,
        type TEXT NOT NULL,
        category TEXT,
        value_cents INTEGER NOT NULL,
        description TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS order_items (
        id TEXT PRIMARY KEY,
        order_id TEXT NOT NULL,
        item_id TEXT,
        item_name TEXT NOT NULL,
        quantity INTEGER NOT NULL DEFAULT 1,
        price_cents INTEGER NOT NULL DEFAULT 0,
        options_json TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS audit_logs (
        id TEXT PRIMARY KEY,
        restaurant_id TEXT NOT NULL,
        user_id TEXT,
        action TEXT NOT NULL,
        resource TEXT,
        resource_id TEXT,
        payload TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS notification_logs (
        id TEXT PRIMARY KEY,
        order_id TEXT,
        channel TEXT,
        status TEXT,
        payload TEXT,
        phone TEXT,
        event TEXT,
        message TEXT,
        provider TEXT,
        error_message TEXT,
        reason TEXT,
        recipient_role TEXT,
        idempotency_key TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS whatsapp_configs (
        restaurant_id TEXT PRIMARY KEY,
        base_url TEXT,
        instance TEXT,
        apikey TEXT,
        active INTEGER DEFAULT 1,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(restaurant_id)
    )`,
    `CREATE TABLE IF NOT EXISTS users (
        id TEXT PRIMARY KEY,
        restaurant_id TEXT NOT NULL,
        name TEXT NOT NULL,
        username TEXT NOT NULL,
        password_hash TEXT NOT NULL,
        role TEXT NOT NULL DEFAULT 'staff',
        last_login DATETIME,
        active INTEGER DEFAULT 1,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(restaurant_id, username)
    )`,
    `CREATE TABLE IF NOT EXISTS order_ratings (
        id TEXT PRIMARY KEY,
        restaurant_id TEXT NOT NULL,
        order_id TEXT NOT NULL,
        customer_id TEXT,
        stars INTEGER NOT NULL DEFAULT 5,
        comment TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS payments (
        id TEXT PRIMARY KEY,
        restaurant_id TEXT NOT NULL,
        order_id TEXT NOT NULL,
        method TEXT,
        amount INTEGER NOT NULL DEFAULT 0,
        status TEXT DEFAULT 'pending',
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS driver_orders (
        id TEXT PRIMARY KEY,
        restaurant_id TEXT NOT NULL,
        driver_id TEXT NOT NULL,
        order_id TEXT NOT NULL,
        status TEXT DEFAULT 'assigned',
        fee_cents INTEGER DEFAULT 0,
        delivery_fee_cents INTEGER DEFAULT 0,
        settled INTEGER DEFAULT 0,
        completed_at DATETIME,
        assigned_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS order_events (
        id TEXT PRIMARY KEY,
        order_id TEXT NOT NULL,
        type TEXT NOT NULL,
        payload TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS customer_addresses (
        id TEXT PRIMARY KEY,
        customer_id TEXT NOT NULL,
        label TEXT,
        street TEXT NOT NULL,
        number TEXT,
        complement TEXT,
        neighborhood TEXT,
        city TEXT,
        is_default INTEGER DEFAULT 0,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
];

export const schemaAlterations: string[] = [
    `ALTER TABLE orders ADD COLUMN customer_name TEXT`,
    `ALTER TABLE orders ADD COLUMN customer_phone TEXT`,
    `ALTER TABLE orders ADD COLUMN source TEXT DEFAULT 'online'`,
    `ALTER TABLE orders ADD COLUMN notes TEXT`,
    `ALTER TABLE orders ADD COLUMN payment_qr_code TEXT`,
    `ALTER TABLE orders ADD COLUMN payment_qr_base64 TEXT`,
    `ALTER TABLE orders ADD COLUMN payment_reference TEXT`,
    `ALTER TABLE orders ADD COLUMN external_id TEXT`,
    `ALTER TABLE orders ADD COLUMN tax_id TEXT`,
    `ALTER TABLE orders ADD COLUMN is_surge INTEGER DEFAULT 0`,
    `ALTER TABLE orders ADD COLUMN is_happy_hour INTEGER DEFAULT 0`,
    `ALTER TABLE orders ADD COLUMN rating INTEGER`,
    `ALTER TABLE orders ADD COLUMN feedback TEXT`,
    `ALTER TABLE orders ADD COLUMN paid_at DATETIME`,
    `ALTER TABLE driver_orders ADD COLUMN assigned_at DATETIME DEFAULT CURRENT_TIMESTAMP`,
    `ALTER TABLE driver_orders ADD COLUMN delivery_fee_cents INTEGER DEFAULT 0`,
    `ALTER TABLE driver_orders ADD COLUMN settled INTEGER DEFAULT 0`,
    `ALTER TABLE driver_orders ADD COLUMN completed_at DATETIME`,
    `ALTER TABLE option_groups ADD COLUMN sort_order INTEGER DEFAULT 0`,
    `ALTER TABLE option_items ADD COLUMN sort_order INTEGER DEFAULT 0`,
    `ALTER TABLE restaurants ADD COLUMN custom_domain TEXT`,
    `ALTER TABLE restaurants ADD COLUMN store_status TEXT DEFAULT 'open'`,
    `ALTER TABLE restaurants ADD COLUMN prep_time_minutes INTEGER DEFAULT 30`,
    `ALTER TABLE restaurants ADD COLUMN delivery_fee_cents INTEGER DEFAULT 500`,
    `ALTER TABLE restaurants ADD COLUMN min_order_cents INTEGER DEFAULT 0`,
    `ALTER TABLE restaurants ADD COLUMN slogan TEXT`,
    `ALTER TABLE restaurants ADD COLUMN theme TEXT DEFAULT 'light'`,
    `ALTER TABLE restaurants ADD COLUMN theme_id TEXT`,
    `ALTER TABLE restaurants ADD COLUMN font_family TEXT`,
    `ALTER TABLE restaurants ADD COLUMN temp_close_reason TEXT`,
    `ALTER TABLE restaurants ADD COLUMN can_accept_orders INTEGER DEFAULT 1`,
    `ALTER TABLE restaurants ADD COLUMN facebook_pixel_id TEXT`,
    `ALTER TABLE restaurants ADD COLUMN google_analytics_id TEXT`,
    `ALTER TABLE restaurants ADD COLUMN tiktok_pixel_id TEXT`,
    `ALTER TABLE restaurants ADD COLUMN timezone TEXT`,
    `ALTER TABLE restaurants ADD COLUMN opening_hours TEXT`,
    `ALTER TABLE restaurants ADD COLUMN max_orders_simultaneous INTEGER`,
    `ALTER TABLE customers ADD COLUMN tags TEXT`,
    `ALTER TABLE customers ADD COLUMN notes TEXT`,
    `ALTER TABLE customers ADD COLUMN referral_code TEXT`,
    `ALTER TABLE customers ADD COLUMN otp_expires_at DATETIME`,
    `ALTER TABLE customers ADD COLUMN birthday TEXT`,
    `ALTER TABLE menu_items ADD COLUMN tags TEXT`,
    `ALTER TABLE inventory_items ADD COLUMN sku TEXT`,
    `ALTER TABLE inventory_items ADD COLUMN unit TEXT`,
    `ALTER TABLE inventory_items ADD COLUMN min_stock INTEGER DEFAULT 0`,
    `ALTER TABLE inventory_items ADD COLUMN cost_cents INTEGER DEFAULT 0`,
    `ALTER TABLE inventory_items ADD COLUMN active INTEGER DEFAULT 1`,
    `ALTER TABLE inventory_items ADD COLUMN category TEXT`,
    `ALTER TABLE drivers ADD COLUMN last_dispatch_at DATETIME`,
    `ALTER TABLE drivers ADD COLUMN rating REAL DEFAULT 5`,
    `ALTER TABLE cash_sessions ADD COLUMN user_id TEXT`,
    `ALTER TABLE cash_sessions ADD COLUMN initial_value_cents INTEGER DEFAULT 0`,
    `ALTER TABLE cash_sessions ADD COLUMN final_value_cents INTEGER`,
    `ALTER TABLE cash_sessions ADD COLUMN expected_value_cents INTEGER`,
    `ALTER TABLE notification_logs ADD COLUMN phone TEXT`,
    `ALTER TABLE notification_logs ADD COLUMN event TEXT`,
    `ALTER TABLE notification_logs ADD COLUMN message TEXT`,
    `ALTER TABLE notification_logs ADD COLUMN provider TEXT`,
    `ALTER TABLE notification_logs ADD COLUMN error_message TEXT`,
    `ALTER TABLE notification_logs ADD COLUMN reason TEXT`,
    `ALTER TABLE notification_logs ADD COLUMN recipient_role TEXT`,
    `ALTER TABLE notification_logs ADD COLUMN idempotency_key TEXT`,
    `ALTER TABLE whatsapp_configs ADD COLUMN base_url TEXT`,
    `ALTER TABLE whatsapp_configs ADD COLUMN instance TEXT`,
    `ALTER TABLE whatsapp_configs ADD COLUMN apikey TEXT`,
    `ALTER TABLE whatsapp_configs ADD COLUMN active INTEGER DEFAULT 1`,
    `ALTER TABLE whatsapp_configs ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP`,
    `ALTER TABLE whatsapp_configs ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP`,
];

export function toPostgresSql(sql: string): string {
    return sql.replace(/\bDATETIME\b/g, 'TIMESTAMPTZ');
}
