import 'dart:async';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:client_app/core/state/cart_state.dart';
import 'package:client_app/core/services/customer_repository.dart';
import 'package:client_app/core/services/order_repository.dart';
import 'package:client_app/core/models/order.dart';
import 'package:client_app/core/services/backend_api_client.dart';

class CheckoutPage extends StatefulWidget {
  const CheckoutPage({super.key});

  @override
  State<CheckoutPage> createState() => _CheckoutPageState();
}

class _CheckoutPageState extends State<CheckoutPage> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _addressController = TextEditingController();
  final _observationController = TextEditingController();
  String _paymentMethod = 'Pix';
  bool _isLoading = false;

  @override
  void dispose() {
    _nameController.dispose();
    _addressController.dispose();
    _observationController.dispose();
    super.dispose();
  }

  String _buildWhatsAppMessage({String? orderNumber}) {
    final items = context.read<CartState>().items;
    final itemsList = items
        .map((item) =>
            '• ${item.name} x${item.quantity} – R\$ ${item.total.toStringAsFixed(2)}')
        .join('\n');

    final total = context.read<CartState>().totalPrice;
    final orderInfo = orderNumber != null ? '\n📋 Pedido: $orderNumber' : '';
    
    final message = '''🛒 Novo Pedido - X Açaí Delivery$orderInfo

Itens:
$itemsList

Total: R\$ ${total.toStringAsFixed(2)}

Nome: ${_nameController.text}
Endereço: ${_addressController.text}
Pagamento: $_paymentMethod
${_observationController.text.isNotEmpty ? '\nObservação: ${_observationController.text}' : ''}''';

    return message;
  }

  Future<void> _sendToWhatsApp() async {
    if (!_formKey.currentState!.validate()) {
      return;
    }

    setState(() => _isLoading = true);

    try {
      final cartState = context.read<CartState>();
      final orderRepository = OrderRepository();
      final customerRepository = CustomerRepository();

      // 1. Get or create customer
      final customer = await customerRepository.getOrCreateCustomer(
        name: _nameController.text,
        phone: '', // We don't have phone, can add later
        address: _addressController.text,
        notes: _observationController.text.isNotEmpty
            ? _observationController.text
            : null,
      );

      // 2. Create order
      final orderItems = cartState.items
          .map((item) => OrderItem(
                productId: 'menu_${item.name.replaceAll(' ', '_')}',
                name: item.name,
                unitPrice: item.price,
                quantity: item.quantity,
                lineTotal: item.total,
              ))
          .toList();

      final newOrder = DeliveryOrder(
        id: DateTime.now().millisecondsSinceEpoch.toString(),
        orderNumber: '', // will be generated by repository
        status: OrderStatus.placed,
        items: orderItems,
        subtotal: cartState.totalPrice,
        total: cartState.totalPrice,
        paymentMethod: _paymentMethod,
        customerName: _nameController.text,
        customerPhone: null,
        address: _addressController.text,
        notes: _observationController.text.isNotEmpty
            ? _observationController.text
            : null,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        customerId: customer.id,
      );

      // 3. Save order to Firestore
      final savedOrder = await orderRepository.createOrder(order: newOrder);

      // 3b. Notify backend (async, don't block on failure)
      unawaited(
        BackendApiClient.createOrder(
          customerId: customer.id,
          items: orderItems
              .map((item) => {
                    'productId': item.productId,
                    'name': item.name,
                    'unitPrice': item.unitPrice,
                    'quantity': item.quantity,
                  })
              .toList(),
          total: cartState.totalPrice,
          paymentMethod: _paymentMethod,
          address: _addressController.text,
          notes: _observationController.text.isNotEmpty
              ? _observationController.text
              : null,
        ),
      );

      // 4. Build WhatsApp message with order number
      final message = _buildWhatsAppMessage(orderNumber: savedOrder.orderNumber);
      final encodedMessage = Uri.encodeComponent(message);
      final whatsappUrl = 'https://wa.me/5511987470862?text=$encodedMessage';

      // 5. Open WhatsApp
      await launchUrl(Uri.parse(whatsappUrl));

      // 6. Clear cart
      cartState.clearCart();

      if (mounted) {
        // Show success message
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Pedido ${savedOrder.orderNumber} criado com sucesso!'),
            backgroundColor: Colors.green,
          ),
        );
        // Navigate back to menu
        Navigator.of(context).pop();
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Erro ao processar pedido: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
      debugPrint('Checkout error: $e');
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Checkout'),
        centerTitle: true,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text(
                'Dados de Entrega',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _nameController,
                decoration: const InputDecoration(
                  labelText: 'Nome',
                  border: OutlineInputBorder(),
                ),
                validator: (value) =>
                    value?.isEmpty ?? true ? 'Nome obrigatório' : null,
              ),
              const SizedBox(height: 12),
              TextFormField(
                controller: _addressController,
                decoration: const InputDecoration(
                  labelText: 'Endereço',
                  border: OutlineInputBorder(),
                ),
                validator: (value) =>
                    value?.isEmpty ?? true ? 'Endereço obrigatório' : null,
                minLines: 2,
                maxLines: 3,
              ),
              const SizedBox(height: 12),
              TextFormField(
                controller: _observationController,
                decoration: const InputDecoration(
                  labelText: 'Observação (opcional)',
                  border: OutlineInputBorder(),
                  hintText: 'Ex: sem cobertura, com mel, etc',
                ),
                minLines: 1,
                maxLines: 2,
              ),
              const SizedBox(height: 16),
              const Text(
                'Forma de Pagamento',
                style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
              ),
              const SizedBox(height: 8),
              DropdownButton<String>(
                value: _paymentMethod,
                isExpanded: true,
                onChanged: _isLoading
                    ? null
                    : (value) {
                        if (value != null) {
                          setState(() => _paymentMethod = value);
                        }
                      },
                items: const [
                  DropdownMenuItem(value: 'Pix', child: Text('Pix')),
                  DropdownMenuItem(value: 'Cartão', child: Text('Cartão')),
                  DropdownMenuItem(value: 'Dinheiro', child: Text('Dinheiro')),
                ]
                    .map((item) => DropdownMenuItem(
                          value: item.value,
                          child: item.child,
                        ))
                    .toList(),
              ),
              const SizedBox(height: 24),
              Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: Colors.grey[100],
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text(
                      'Resumo do Pedido',
                      style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
                    ),
                    const SizedBox(height: 8),
                    ...context.read<CartState>().items.map((item) => Row(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: [
                            Text('${item.name} x${item.quantity}'),
                            Text('R\$ ${item.total.toStringAsFixed(2)}'),
                          ],
                        )),
                    const Divider(height: 16),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        const Text(
                          'Total:',
                          style: TextStyle(fontWeight: FontWeight.bold),
                        ),
                        Text(
                          'R\$ ${context.read<CartState>().totalPrice.toStringAsFixed(2)}',
                          style: const TextStyle(
                            fontWeight: FontWeight.bold,
                            fontSize: 18,
                            color: Colors.green,
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 24),
              SizedBox(
                width: double.infinity,
                height: 48,
                child: ElevatedButton.icon(
                  onPressed: _isLoading ? null : _sendToWhatsApp,
                  icon: _isLoading
                      ? const SizedBox(
                          width: 20,
                          height: 20,
                          child: CircularProgressIndicator(
                            strokeWidth: 2,
                            valueColor:
                                AlwaysStoppedAnimation<Color>(Colors.white),
                          ),
                        )
                      : const Icon(Icons.send),
                  label: Text(_isLoading ? 'Enviando...' : 'Enviar Pedido'),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.green,
                    foregroundColor: Colors.white,
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
